name: Continuous Integration
on: push
jobs:
  ci-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build

      - uses: appleboy/ssh-action@v1 
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            rm -r "/home/${{ secrets.USERNAME }}/${{ github.event.repository.name }}/dist"

      - uses: appleboy/scp-action@v1
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          source: ./dist
          target: "/home/${{ secrets.USERNAME }}/${{ github.event.repository.name }}"
